### PR TITLE
allow implicit cast from `S` to `?&const S`

### LINKED ISSUE #731: Can't pass non-nullable pointer to nullable
Seems like this should be allowed as implicitly compatible (of course, not the other way around):

```
D:\Workspace\beast\src\main.zig:120:34: error: expected type '?&const ?&const u8', found '&const &const u8'
    c.glShaderSource(shader, 1, &sources, &sizes);
```

### PR DESCRIPTION
**Pull request by bnoordhuis**
Allow implicit casts from container types to nullable const pointers to
said container type.  That is:

    fn f() void {
        const s = S {};
        g(s);   // Works.
        g(&s);  // So does this.
    }

    fn g(_: ?&const S) void {  // Nullable const pointer.
    }

Fixes #731.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
I should mention that it doesn't work for pointers-to-pointers.  This is still an error:
```zig
const s = S() {};
const p = &s;
f(&p);  // fn f(_: ?&const ?&const S) {}
```
Is that a safe transformation to make?

**Comment by bnoordhuis** [comment]
Oh, and another question: should this work?
```
const s = S {};
try f(&s);  // fn f(_: error!?&const S) !void {}
```
I ask because it doesn't work with `error!&const S` either.  `error!S` does however.

**Comment by andrewrk** [comment]
> are non-nullable pointers a compile-time thing only? No effect on the size of the object?

Correct. Nullable pointers are guaranteed to be pointer sized.

I think that the example with an error set should work too.

Related is #733. After this is done we *might* remove the ability to cast `T` to `&const T`.

**Comment by andrewrk** [comment]
@bnoordhuis,

Once again, thank you for a high quality, high impact pull request. Would you like to become one of the owners of the zig-lang organization and have commit access?

**Comment by bnoordhuis** [comment]
> Correct. Nullable pointers are guaranteed to be pointer sized.  I think that the example with an error set should work too.

Okay, I'll chip at it some more.

> Would you like to become one of the owners of the zig-lang organization and have commit access?

I'd be honored!

**Pull request merged**
