### PR TITLE
Add Blake2X hash functions

### PR DESCRIPTION
**Pull request by tiehuis**
The truncated output variants currently are dependent on a more complete bigint implementation in the compiler.

No speed measurements just yet.

Also, I'm tempted to change the way we return values. Instead of an integer just reverting to a more standard byte array. Not really a huge benefit using integers except for marginally easier comparisons/printing.

### CODE REVIEW

**Comment by andrewrk** [comment]
I'll work on big int rem today

**Comment by andrewrk** [comment]
You should be good as of 84d8584c5b315c24a00fa444d758a6b78f80f4a0

**Comment by andrewrk** [comment]
I fixed the above bug with remainder division in 6a95b88d1b3a619532feedffc674fc4b5bf7517b but the blake tests when uncommented still don't pass for me. Probably there is still something wrong with bigint. See #405

**Comment by tiehuis** [comment]
Awesome. I'll actually change the return method to fill a input slice I think. If we add extendable-output hash functions (such as SHAKE) we will want to avoid the copies anyway and the API consistency will be a bit cleaner.

**Comment by tiehuis** [comment]
Updated all the crypto functions to fill a result buffer. All tests passing now.

**Pull request merged**
