### PR TITLE
Added support for exporting of C field expressions

### LINKED ISSUE #619: parsec doesn't generate a symbol when the target of a macro is a field within a union.
This format is common within OpenGL loaders. 

```
typedef unsigned int GLbitfield;
typedef void (*PFNGLCLEARPROC) (GLbitfield mask);

typedef void(*OpenGLProc)(void);
union OpenGLProcs {
    OpenGLProc ptr[1];
    struct {
        PFNGLCLEARPROC Clear;
    } gl;
};

extern union OpenGLProcs glProcs;
#define glClearUnion glProcs.gl.Clear
#define glClearPFN PFNGLCLEARPROC
```

zig output:

```
pub const GLbitfield = c_uint;
pub const PFNGLCLEARPROC = ?extern fn(GLbitfield);
pub const OpenGLProc = ?extern fn();
pub const glClearPFN = PFNGLCLEARPROC;
```

### PR DESCRIPTION
**Pull request by dimenus**
This closes #619

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
I don't understand what this PR is adding. This is my guess after reading the test included in this PR:

```c
#define foo a.b
```

**Comment by dimenus** [comment]
@thejoshwolfe Check the issue I referenced. It creates support for c macros that whose targets are fields of unions / structs. Right now the classic OpenGL function loader (e.g. gl3w) doesn't work.

**Comment by andrewrk** [comment]
Let's try to get this integrated with the inline-function generator like we have for this test case:

```zig
    cases.add("generate inline func for #define global extern fn",
        \\extern void (*fn_ptr)(void);
        \\#define foo fn_ptr
        \\
        \\extern char (*fn_ptr2)(int, float);
        \\#define bar fn_ptr2
    ,
        \\pub extern var fn_ptr: ?extern fn();
    ,
        \\pub inline fn foo() {
        \\    (??fn_ptr)()
        \\}
    ,
        \\pub extern var fn_ptr2: ?extern fn(c_int, f32) -> u8;
    ,
        \\pub inline fn bar(arg0: c_int, arg1: f32) -> u8 {
        \\    (??fn_ptr2)(arg0, arg1)
        \\}
    );
```

So I think we should try to get this to work, instead of outputing:

```zig
pub const glClearUnion = glProcs.gl.Clear;
```

we should output:

```zig
pub inline fn glClearUnion(arg0: GLbitfield) {
    (??glProcs.gl.Clear)(arg0)
}
```

I think it's reasonable to assume that if you `#define foo fn_ptr` then you intend to call foo as a function, which asserts that fn_ptr is non-null. Indeed this is how the OpenGL API works.


Unrelated, appveyor tests failed:
```
C:/projects/zig-d3l86/src/c_tokenizer.cpp: In function 'void begin_token(CTokenize*, CTokId)':
C:/projects/zig-d3l86/src/c_tokenizer.cpp:104:12: error: enumeration value 'CTokIdDot' not handled in switch [-Werror=switch]
     switch (id) {
            ^
cc1plus.exe: all warnings being treated as errors
make[2]: *** [CMakeFiles/zig.dir/build.make:183: CMakeFiles/zig.dir/src/c_tokenizer.cpp.obj] Error 1
```

**Comment by andrewrk** [comment]
@dimenus your intuition about `macro_symbols` and  `macro_table` not needing to be separate was correct.

**Pull request merged**
