### PR TITLE
rework std.base64 api

### LINKED ISSUE #611: std.base64 should support reporting errors and ignoring non alphabet characters
[Such as it is, the spec](https://tools.ietf.org/html/rfc4648)

Relevant passage: 

```
Implementations MUST reject the encoded data if it contains
   characters outside the base alphabet when interpreting base-encoded
   data, unless the specification referring to this document explicitly
   states otherwise.  Such specifications may instead state, as MIME
   does, that characters outside the base encoding alphabet should
   simply be ignored when interpreting data ("be liberal in what you
   accept")
```

Currently, `encode` accepts all incoming data. 

For reference:

```
VGltZSBwcmVzZW50IGFuZCB0aW1lIHBhc3QKQXJlIGJvdGggcGVyaGFwcyBw
cmVzZW50IGluIHRpbWUgZnV0dXJlLApBbmQgdGltZSBmdXR1cmUgY29udGFp
bmVkIGluIHRpbWUgcGFzdC4KSWYgYWxsIHRpbWUgaXMgZXRlcm5hbGx5IHBy
ZXNlbnQKQWxsIHRpbWUgaXMgdW5yZWRlZW1hYmxlLgpXaGF0IG1pZ2h0IGhh
dmUgYmVlbiBpcyBhbiBhYnN0cmFjdGlvbgpSZW1haW5pbmcgYSBwZXJwZXR1
YWwgcG9zc2liaWxpdHkKT25seSBpbiBhIHdvcmxkIG9mIHNwZWN1bGF0aW9u
Lgo=
```
when decoded with zig yields:

```
Time present and time past
Are both perhaps pÉÍ¹Ð¥¸Ñ¥µÕÑÕÉ°)¹Ñ¥µÕÑÕÉ½¹Ñ¤æVBâFÖR7Bà¤bÆÂFÖR2WFW&æÆÇ0\Ù[[[YH\È[YY[XXKÚ]ZYÚ@ve been is an abstraction
Remaining a perpetu°Á½ÍÍ¥¥±¥Ñä)=¹±ä¥¸Ý½É±½ÍÁÕ±Ñ¥½¼à¤
```
It makes sense to either validate and reject nonconforming input or ignore it.  Bsd's `base64` utility seems to ignore whitespace and return an error on other characters.

### PR DESCRIPTION
**Pull request by thejoshwolfe**
* rename decode to decodeExactUnsafe.
* add decodeExact, which checks for invalid chars and padding.
* add decodeWithIgnore, which also allows ignoring chars.
* alphabets are supplied to the decoders with their
  char-to-index mapping already built, which enables it to be
  done at comptime.
* all decode/encode apis except decodeWithIgnore require dest
  to be the exactly correct length. This is calculated by a
  calc function corresponding to each api. These apis no longer
  return the dest parameter.
* for decodeWithIgnore, an exact size cannot be known a priori.
  Instead, a calc function gives an upperbound, and a runtime
  error is returned in case of overflow. decodeWithIgnore
  returns the number of bytes written to dest.

closes #611

### CODE REVIEW

**Comment by thejoshwolfe** [comment]
Now that i'm looking at it, i want to move the decode functions into the "Alphabet" structs, and rename the "Alphabet" structs to "Decoder".

**Comment by andrewrk** [comment]
Looks good to me, feel free to merge. However I'd like to suggest not using "unsafe" to communicate that something could be an undefined value. "unsafe" usually communicates that something could be undefined behavior which is very different.

**Comment by thejoshwolfe** [comment]
would "unchecked" be better than "unsafe"?

**Comment by andrewrk** [comment]
yes

**Comment by thejoshwolfe** [comment]
actually `calcDecodedSizeExactUnsafe()` uses `@divExact()` to assume the input length is a multiple of 4. That is actually undefined behavior if that assumption is not met. And that assumption is transitively included in all the other Unsafe methods, so Unsafe is a correct description, albeit just for that one assumption. Invalid characters are still defined behavior with undefined values.

**Comment by andrewrk** [comment]
Ok sounds like it's good to merge then

**Comment by thejoshwolfe** [comment]
Do you have an opinion on this new OOP-looking API? Seems like the namespace is cleaner, and I like the new comptime asserts for encoding.

**Comment by thejoshwolfe** [comment]
I just started trying to write a simple base64 transform command line program using this api, and i've immediately run into a design limitation 😞. The existing API is hostile to streaming.

New idea. Replace the Base64DecoderWithIgnore class with a streaming decoder. It's already behaving a lot like a streaming decoder internally anyway. That can be an improvement after this PR is merged though. And I probably won't have time to do that in the immediate future.

**Pull request merged**
