### PR TITLE
Add support for event loop and basic network listeners, and a general-purpose memory allocator

### PR DESCRIPTION
**Pull request by bscheinman**

### CODE REVIEW

**Comment by andrewrk** [comment]
In your general purpose allocator, the part where it actually needs to do the syscall to allocate memory is unimplemented. 

I have a suggested solution! This allocator can accept another allocator upon initialization, which it uses to make the underlying raw_alloc allocations. 

Then the user of this API can pass in a DirectAllocator, which always calls the system API to allocate/free directly.

You can see this pattern in std/special/build_runner.zig.

**Comment by andrewrk** [comment]
This is quite a lot of exciting stuff. Can you break this into a series of smaller, independently unit-tested, easier-to-review pull requests?

**Comment by bscheinman** [comment]
Closing this PR, and I will reopen a number of smaller independent ones as suggested.

**Comment by kristate** [comment]
@bscheinman @andrewrk What is the latest on this?
Can we get a PR/Issue open to start working on networking?

**Comment by andrewrk** [comment]
Here's something
https://gist.github.com/andrewrk/d48c8c9ca0fb67bf6d7c0bed744d82ce

I've got some work in a branch too. More work planned after Pointer Reform (see #770) is done.

**Comment by kristate** [comment]
@andrewrk cool -- there is a lot of work that has been put into this PR.

Would it be better to directly hack on `std` or build-out a module and then integrate later?

Is there a google hang-out or something that we can join to work on hacking together?

Sorry to ask here! Thanks!

**Comment by andrewrk** [comment]
> there is a lot of work that has been put into this PR.

Everything this PR does exists in std.event using coroutines. I have yet to document that language feature though. The general purpose allocator in this PR was never finished.


> Would it be better to directly hack on std or build-out a module and then integrate later?

I know @tiehuis likes to build out separate repositories before submitting a pull request to zig. You're welcome to make pull requests directly against std. I would recommend first filing an issue with a proposal explaining the use case that you're trying to solve and how you propose going about solving it - that way if it's something already planned or related to something already planned we can figure out the best way to go about it.

> Is there a google hang-out or something that we can join to work on hacking together?

The `#zig` channel on freenode is a good place to collaborate with the zig community.

> Sorry to ask here! Thanks!

No worries. Hope to see you around

**Pull request closed without merging**
